/**
 * The 15×15 board (docs/LUDO_RULES.md §1, §7, §8, §12).
 *
 * **What a tap picks is a pawn, not a square.** The die decides where a pawn
 * goes, so there is nothing to aim at and no second stage: the pawns the rules
 * allow are pressable, everything else on the board is drawn and inert. That
 * is also the whole of this game's help (§7) — an illegal tap is not scolded
 * because there is nothing there to tap.
 *
 * **Only the squares that mean something are drawn**: the fifty-two ring
 * squares, the four home columns of six, the sixteen yard slots, and the goal.
 * The other hundred-odd cells of the grid are the yards' own blocks and empty
 * space; making all 225 of them elements would put two hundred inert nodes in
 * front of every screen reader and every hit test.
 *
 * **The hit area is bigger than the square, and only movable pawns have one.**
 * At 320px a square is about 21px across, which no finger can pick out, so a
 * movable pawn's button grows a transparent target well past its own square.
 * That is safe precisely because it is only movable pawns: everything else has
 * `pointer-events: none`, so an enlarged target can never swallow a tap meant
 * for a neighbour it overlaps.
 *
 * Pawns may legally share a square (§2.4), including with enemies on a safe
 * square, so pawns on one square are drawn fanned apart and each is its own
 * element. A fanned pawn's target is trimmed: the enlarged one is for a pawn
 * standing alone, where there is nothing beside it to steal.
 *
 * Geometry is generated by rotation rather than written out four times. Seat
 * 0's thirteen ring squares, its home column, and its four yard slots are the
 * only coordinates in this file; the other three seats are quarter-turns of
 * those, which is what makes "seat s enters at global square 13s" (§1) true of
 * the drawing as well as of the numbers.
 */
import { memo, useEffect, useRef, type CSSProperties } from 'react';
import { useSettings } from '@/state/SettingsContext';
import { useReducedMotion } from '@/ui/useReducedMotion';
import {
  globalSquareOf,
  isSafeSquare,
  HOME_COLUMN_LENGTH,
  HOME_PROGRESS,
  PAWNS_PER_SEAT,
  RING_SIZE,
  SEATS,
  SEAT_START_STRIDE,
  YOU,
  type BySeat,
  type Seat,
} from '../../game';
import { pawnLabel, placeLabel } from './seatText';

/** The board is fifteen squares on a side (§1). */
export const GRID_SIZE = 15;

/** One cell of the grid, row and column both counted from zero. */
export interface Cell {
  readonly row: number;
  readonly col: number;
}

/** One quarter-turn clockwise about the board's centre — seat s to seat s+1. */
const turned = (cell: Cell): Cell => ({ row: cell.col, col: GRID_SIZE - 1 - cell.row });

function turnedBy(cell: Cell, quarters: number): Cell {
  let out = cell;
  for (let turn = 0; turn < quarters; turn++) out = turned(out);
  return out;
}

/**
 * Seat 0's thirteen ring squares, in the order a pawn walks them: up the near
 * lane of its own arm, round the corner of the yard, along the next arm, and
 * over that arm's tip. The first is seat 0's entrance (global square 0); the
 * last is the square a quarter-turn away from seat 1's entrance, so
 * `turnedBy` lays the remaining thirty-nine down exactly 13 apart (§1).
 */
const QUADRANT: readonly Cell[] = [
  { row: 12, col: 6 },
  { row: 11, col: 6 },
  { row: 10, col: 6 },
  { row: 9, col: 6 },
  { row: 8, col: 5 },
  { row: 8, col: 4 },
  { row: 8, col: 3 },
  { row: 8, col: 2 },
  { row: 8, col: 1 },
  { row: 8, col: 0 },
  { row: 7, col: 0 },
  { row: 6, col: 0 },
  { row: 6, col: 1 },
];

/** Every ring square, by its global number. */
export const RING_CELLS: readonly Cell[] = Array.from({ length: RING_SIZE }, (_, square) =>
  turnedBy(QUADRANT[square % SEAT_START_STRIDE]!, Math.floor(square / SEAT_START_STRIDE)),
);

/** Seat 0's home column, from the square it turns off onto to the last one. */
const HOME_COLUMN: readonly Cell[] = Array.from({ length: HOME_COLUMN_LENGTH }, (_, step) => ({
  row: 13 - step,
  col: 7,
}));

/** Seat 0's four yard slots — one per pawn, so a yard never stacks. */
const YARD_SLOTS: readonly Cell[] = [
  { row: 10, col: 1 },
  { row: 10, col: 3 },
  { row: 12, col: 1 },
  { row: 12, col: 3 },
];

/** Seat 0's yard block, as a grid area. The other three are quarter-turns. */
const YARD_BLOCKS: BySeat<Cell> = [
  { row: 9, col: 0 },
  { row: 0, col: 0 },
  { row: 0, col: 9 },
  { row: 9, col: 9 },
];

/** The middle of the board: every pawn that gets home stands here. */
const GOAL_CELL: Cell = { row: 7, col: 7 };

export const homeColumnCell = (seat: Seat, step: number): Cell =>
  turnedBy(HOME_COLUMN[step]!, seat);

export const yardCell = (seat: Seat, pawn: number): Cell => turnedBy(YARD_SLOTS[pawn]!, seat);

/**
 * Where a pawn is drawn. The one number that is a pawn's whole position
 * (game/types.ts) is unfolded here and nowhere else in the UI.
 */
export function cellOf(seat: Seat, pawn: number, progress: number): Cell {
  if (progress === 0) return yardCell(seat, pawn);
  if (progress === HOME_PROGRESS) return GOAL_CELL;
  const square = globalSquareOf(seat, progress);
  if (square !== null) return RING_CELLS[square]!;
  return homeColumnCell(seat, progress - RING_SIZE - 1);
}

/** Places an element on the grid. Grid lines count from one; cells from zero. */
const at = (cell: Cell, span = 1): CSSProperties => ({
  gridRow: `${cell.row + 1} / span ${span}`,
  gridColumn: `${cell.col + 1} / span ${span}`,
});

/** The longest a pawn's walk is allowed to take (§12: 220ms is the ceiling). */
const SLIDE_MS_MAX = 220;
const SLIDE_MS_PER_CELL = 26;

const keyOf = (cell: Cell): string => `${cell.row},${cell.col}`;

interface Placed {
  readonly id: string;
  readonly seat: Seat;
  readonly pawn: 0 | 1 | 2 | 3;
  readonly progress: number;
  readonly cell: Cell;
}

export interface LudoBoardProps {
  pawns: BySeat<readonly [number, number, number, number]>;
  /** Which of the player's pawns the rules allow right now (§7). */
  movable: readonly (0 | 1 | 2 | 3)[];
  /** False while a dialog is up or the match is over: nothing is pressable. */
  playing: boolean;
  onPawn: (pawn: 0 | 1 | 2 | 3) => void;
}

export const LudoBoard = memo(function LudoBoard({
  pawns,
  movable,
  playing,
  onPawn,
}: LudoBoardProps) {
  const { t } = useSettings();
  const reducedMotion = useReducedMotion();

  /** Where each pawn stood at the previous commit, so a walk has a start. */
  const before = useRef<Map<string, Cell>>(new Map());

  const placed: Placed[] = [];
  for (const seat of SEATS) {
    for (let index = 0; index < PAWNS_PER_SEAT; index++) {
      const pawn = index as 0 | 1 | 2 | 3;
      const progress = pawns[seat][index]!;
      placed.push({
        id: `${seat}-${pawn}`,
        seat,
        pawn,
        progress,
        cell: cellOf(seat, pawn, progress),
      });
    }
  }

  /** How many pawns share each square, and which of them this one is. */
  const crowd = new Map<string, number>();
  for (const one of placed) crowd.set(keyOf(one.cell), (crowd.get(keyOf(one.cell)) ?? 0) + 1);
  const seen = new Map<string, number>();

  const occupied = new Set(placed.map((one) => keyOf(one.cell)));
  const movableSet = new Set(playing ? movable : []);

  useEffect(() => {
    const next = new Map<string, Cell>();
    for (const seat of SEATS) {
      for (let index = 0; index < PAWNS_PER_SEAT; index++) {
        next.set(`${seat}-${index}`, cellOf(seat, index, pawns[seat][index]!));
      }
    }
    before.current = next;
  }, [pawns]);

  return (
    <div className="ld-board" role="group" aria-label={t('ludoBoardLabel')}>
      {SEATS.map((seat) => (
        <div
          key={`yard-${seat}`}
          className={`ld-yard ld-seat-${seat}`}
          style={at(YARD_BLOCKS[seat], 6)}
          aria-hidden="true"
        />
      ))}

      {RING_CELLS.map((cell, square) => {
        const safe = isSafeSquare(square);
        // The four entrance squares are tinted with the seat that leaves the
        // yard onto them, so a pawn's first square looks like its own.
        const entrance = square % SEAT_START_STRIDE === 0 ? square / SEAT_START_STRIDE : null;
        return (
          <div
            key={`ring-${square}`}
            className={[
              'ld-cell',
              'ld-track',
              safe ? 'ld-safe' : '',
              entrance === null ? '' : `ld-entrance ld-seat-${entrance}`,
            ]
              .filter(Boolean)
              .join(' ')}
            style={at(cell)}
            // A safe square standing empty still says so: it is the one thing
            // about a bare square that changes what happens on it (§2.3).
            {...(safe && !occupied.has(keyOf(cell))
              ? { role: 'img', 'aria-label': t('ludoSafeSquare') }
              : { 'aria-hidden': true })}
          >
            {safe ? <span className="ld-star" aria-hidden="true" /> : null}
          </div>
        );
      })}

      {SEATS.map((seat) =>
        Array.from({ length: HOME_COLUMN_LENGTH }, (_, step) => (
          <div
            key={`home-${seat}-${step}`}
            className={`ld-cell ld-column ld-seat-${seat}`}
            style={at(homeColumnCell(seat, step))}
            aria-hidden="true"
          />
        )),
      )}

      {SEATS.map((seat) =>
        Array.from({ length: PAWNS_PER_SEAT }, (_, slot) => (
          <div
            key={`slot-${seat}-${slot}`}
            className={`ld-cell ld-slot ld-seat-${seat}`}
            style={at(yardCell(seat, slot))}
            aria-hidden="true"
          />
        )),
      )}

      <div className="ld-cell ld-goal" style={at(GOAL_CELL)} aria-hidden="true" />

      {placed.map((one) => {
        const key = keyOf(one.cell);
        const size = crowd.get(key) ?? 1;
        const index = seen.get(key) ?? 0;
        seen.set(key, index + 1);

        const from = before.current.get(one.id);
        const moved =
          !reducedMotion &&
          from !== undefined &&
          (from.row !== one.cell.row || from.col !== one.cell.col);
        const distance =
          from === undefined
            ? 0
            : Math.abs(from.row - one.cell.row) + Math.abs(from.col - one.cell.col);

        const style: CSSProperties = {
          ...at(one.cell),
          // Fanned apart round the middle of the square, so every pawn on a
          // shared square is visible and reachable on its own (§8).
          '--ld-fan': `${(index - (size - 1) / 2) * 26}%`,
          '--ld-lift': String(index),
          ...(moved
            ? {
                '--ld-walk-x': `${(from!.col - one.cell.col) * 100}%`,
                '--ld-walk-y': `${(from!.row - one.cell.row) * 100}%`,
                '--ld-walk-ms': `${Math.min(SLIDE_MS_MAX, Math.max(1, distance) * SLIDE_MS_PER_CELL)}ms`,
              }
            : null),
        } as CSSProperties;

        const className = [
          'ld-pawn',
          `ld-seat-${one.seat}`,
          size > 1 ? 'ld-pawn-fanned' : '',
          moved ? 'ld-pawn-walk' : '',
        ]
          .filter(Boolean)
          .join(' ');
        // Remounted whenever the square changes, which is what restarts the
        // walk; a pawn that stayed put keeps its element and does not animate.
        const nodeKey = `${one.id}@${key}`;
        const mark = <span className="ld-mark" aria-hidden="true" />;

        if (one.seat === YOU && movableSet.has(one.pawn)) {
          return (
            <button
              key={nodeKey}
              type="button"
              className={`${className} ld-pawn-live`}
              style={style}
              aria-label={t('ludoMovePawn', { where: placeLabel(t, one.seat, one.progress) })}
              onClick={() => onPawn(one.pawn)}
            >
              {mark}
            </button>
          );
        }
        return (
          <span
            key={nodeKey}
            className={className}
            style={style}
            role="img"
            aria-label={pawnLabel(t, one.seat, one.progress)}
          >
            {mark}
          </span>
        );
      })}
    </div>
  );
});
