/**
 * CrownGrid's app context: a starting point generated by scripts/new-game.mjs.
 * It wires the shell's contract — records load, a home screen, a result
 * worth sharing — so the next step is writing the game, not the plumbing
 * around it.
 *
 * The one placeholder round below (`playPlaceholderRound`) exists only so
 * the stats seam is real rather than decorative: every context in this
 * collection advances its ref immediately before the matching setState call,
 * because React batches one task's updates and a second mutation in that
 * task would otherwise read what the first one just replaced
 * (docs/ARCHITECTURE.md「状態と ref」, src/test/refLeading.test.ts). Replace
 * the round itself; keep the ref-then-setState shape when you do.
 */
import {
  createContext,
  useCallback,
  useContext,
  useMemo,
  useRef,
  useState,
  type ReactNode,
} from 'react';
import { saveRecord } from '../../../storage/repo';
import { flagsSchema, statsSchema, type Flags, type Stats } from '../storage/schemas';

/** Stands in for "a round is in progress" — replace with the real shape. */
interface PlaceholderRound {
  readonly startedAt: number;
}

/** What the result overlay shows. Replace with the game's real outcome. */
export interface LastResult {
  readonly playedAt: number;
}

export interface CrownGridContextValue {
  stats: Stats;
  tutorialCompleted: boolean;
  lastResult: LastResult | null;
  /** Placeholder for "play a round" — wire up the real game here. */
  playPlaceholderRound: () => void;
  dismissResult: () => void;
  completeTutorial: () => void;
  exitToCollection: () => void;
}

const CrownGridContext = createContext<CrownGridContextValue | null>(null);

export interface CrownGridProviderProps {
  initialStats: Stats;
  initialFlags: Flags;
  /** Provided by the shell: hands control back to the collection home. */
  onExit: () => void;
  children: ReactNode;
}

export function CrownGridProvider({
  initialStats,
  initialFlags,
  onExit,
  children,
}: CrownGridProviderProps) {
  const [stats, setStats] = useState<Stats>(initialStats);
  const [flags, setFlags] = useState<Flags>(initialFlags);
  const [round, setRound] = useState<PlaceholderRound | null>(null);
  const [lastResult, setLastResult] = useState<LastResult | null>(null);

  const statsRef = useRef(stats);
  statsRef.current = stats;
  const sessionRef = useRef(round);
  sessionRef.current = round;

  const persistStats = useCallback((next: Stats) => {
    statsRef.current = next;
    setStats(next);
    void saveRecord(statsSchema, next);
  }, []);

  const putSession = useCallback((next: PlaceholderRound | null) => {
    sessionRef.current = next;
    setRound(next);
  }, []);

  const playPlaceholderRound = useCallback(() => {
    putSession({ startedAt: Date.now() });
    persistStats({ ...statsRef.current, played: statsRef.current.played + 1 });
    putSession(null);
    setLastResult({ playedAt: Date.now() });
  }, [persistStats, putSession]);

  const dismissResult = useCallback(() => setLastResult(null), []);

  const completeTutorial = useCallback(() => {
    if (flags.tutorialCompleted) return;
    const next = { ...flags, tutorialCompleted: true };
    setFlags(next);
    void saveRecord(flagsSchema, next);
  }, [flags]);

  const value = useMemo<CrownGridContextValue>(
    () => ({
      stats,
      tutorialCompleted: flags.tutorialCompleted,
      lastResult,
      playPlaceholderRound,
      dismissResult,
      completeTutorial,
      exitToCollection: onExit,
    }),
    [
      stats,
      flags.tutorialCompleted,
      lastResult,
      playPlaceholderRound,
      dismissResult,
      completeTutorial,
      onExit,
    ],
  );

  return <CrownGridContext.Provider value={value}>{children}</CrownGridContext.Provider>;
}

export function useCrownGrid(): CrownGridContextValue {
  const value = useContext(CrownGridContext);
  if (!value) throw new Error('useCrownGrid must be used inside CrownGridProvider');
  return value;
}
